= J-Voting
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: j-voting
:repository: J-Voting

image:https://travis-ci.com/{gitHubUserName}/{repository}.svg?branch=master["Build Status", link="https://travis-ci.com/{gitHubUserName}/{repository}"]

A Java project developed during several sessions of the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 and M2 MIAGE).

The code is hereby published under the MIT License, with the permission of the contributors.


= Java Iteration plan

== Iteration 1 

*Jade & Thomas* :

- Add asSctrictGraph() method in the Preference : + 
Returns an asymetric transitive graph which is an asGraph sub graph. (It contains the (a, b) pairs but not (b, a) pairs in order to have a > b).


*Pierre, Léo and Julien* : 

- Add equals method in ImmutablePreference. +
- Investigation phase on ImmutablePreference and CompletePreference Interfaces (Finding bugs or irrelevances and start correcting them).


Overall goal of the iteration : +
Initiate the Preferences code consolidation before making futur improvements on the Profiles part.



