= J-Voting
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: j-voting
:repository: J-Voting

image:https://travis-ci.com/{gitHubUserName}/{repository}.svg?branch=master["Build Status", link="https://travis-ci.com/{gitHubUserName}/{repository}"]

A Java project developed during several sessions of the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 and M2 MIAGE).

The code is hereby published under the MIT License, with the permission of the contributors.


= Java Iteration plan

== Iteration 1 

*Jade & Thomas* :

Our objective was to replace OldCompletePreferenceImpl used in the whole project by CompletePreferenceImpl. 

To do so, we had to implement methods which were in OldCompletePreferenceImpl but not in CompletePreferenceImpl. In this iteration we have created several methods :

* size() returns the size of the preference, i.e. the number of Sets in it.
* alternativeNumber() returns the number of alternatives in the preference.
* isStrict() says whether the preference is strict or not (no alternatives having the same rank).
* toAlternativeSet() returns a set of alternatives containing all the alternatives of the preference (with no duplicates).
* contains() says whether the preference contains the given alternative.
* isIncludedIn() says wether the preference given contains the current preference (all its alternatives).
* hasSameAlternatives() says wether the two prefenrences have exactly the same alternatives (without considering the order).

We have also made tests in relations with them.

During this task, we removed few warnings in CompletePreferenceTest and in OldCompletePreferenceImpl.


*Pierre, Léo and Julien* : 

A faire






