= J-Voting
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: j-voting
:repository: J-Voting

image:https://travis-ci.com/{gitHubUserName}/{repository}.svg?branch=master["Build Status", link="https://travis-ci.com/{gitHubUserName}/{repository}"]

A Java project developed during several sessions of the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 and M2 MIAGE).

The code is hereby published under the MIT License, with the permission of the contributors.


= Java Iteration plan

== Iteration 1 

*Jade & Thomas* :

Our objective is to replace OldCompletePreferenceImpl used in the whole project by CompletePreferenceImpl. The first step of this goals consists in analysing the OldCompletePreferenceImpl way of functioning and improving the CompletePreferenceImpl class. 

Details are visible here : link:https://github.com/Julienchilhagopian/J-Voting/pull/2[PR#2]. 


*Pierre & Léo* :

Our goal on this iteration is to create a MutableLinearPreferenceImpl class and the interface which implements MutableLinearPreference. This class aims to work on mutable and linear preferences. The number of alternatives can thus evolve, one alternative cannot be equal to another and all the alternatives are comparable two by two.

Details are visible here : link:https://github.com/Julienchilhagopian/J-Voting/pull/3[PR#3]. 


*Julien* : 

SM/PO

== Iteration 2

*Jade & Julien* :

The main goal is still to move towards removing the OldCompletePreferenceImpl class. This time the objective is to upgrade CompletePreferenceImpl without impacting the CompletePreference Interface and respecting the comments of the link:https://github.com/Julienchilhagopian/J-Voting/pull/2[PR#2]. 
Once that the upgraded version of CompletePreferenceImpl is done, the class will be able to replace OldCompletePreferenceImpl used in the whole project.

A detailed report of the CompletePreferenceImpl futur evolutions can be found link:Doc/chapters/FromOldCompletePreferenceImplToCompletePreferenceImpl.adoc[here]

*Léo & Thomas* :

Mettez votre petit texte ici + lien vers votre adoc

*Pierre* :

SM/PO





