= Decorator documentation

====== link:../README.adoc[Summary]

=== What is a decorator and how is it useful ?

The link:https://en.wikipedia.org/wiki/Decorator_pattern[decorator pattern] is a design pattern that allows behavior to be added to an individual object, dynamically, without affecting the behavior of other objects from the same class. In other words, if your object structure can be broken by modifying one of its attributes (ex : set.add(_something_)), it is absolutely necessary to encapsulate the attribute(s) with a decorator to override the dangerous methods (ex : add).

Therefore, when the user will attempt to use one of the risky methods on an attribute, he will actually call the overrided one (decoratorSet.add()) instead of the one he thinks (set.add()) without knowing it.

The decorator has only one attribute called delegate that represents the decorated object. It extends a specific interface. For instance, if the threatened attribute is a set, it will extend ForwardingSet (containing all the Set methods). That is why the decorator has a delegate() method in addition of all the basic methods coming from the interface.


=== Decorators in J-voting

In our project, linearity issues forced us to resort to use decorators. Indeed, we manipulate mutable preferences. In MutableLinearPreferenceImpl, there are 4 attributes that can be modified : 

* a list

* a set 

* a graph

* a voter

This class contains getter methods (for the set and the graph) which is problematic because the user could reach and modify one of these two attributes. Yet, the four attributes always have to be in accordance with each other. Thus, if the set or the graph is modified, so must the other attributes.
Thus, we implemented a decorator for the set extending  link:https://guava.dev/releases/19.0/api/docs/com/google/common/collect/ForwardingSet.html[ForwardingSet] and one for the graph extending link:https://github.com/google/guava/blob/master/guava/src/com/google/common/graph/ForwardingGraph.java[ForwardingGraph] of Guava. It is important to know that ForwardingGraph is not ready to be used for general purposes so we created our own ForwardingGraph copying it. 

[sequence diagram]
