= Annex 2. Change of direction in MutableLinearPreference

====== link:../README.adoc[Summary]

This iteration aims to finalize the Mutable Linear Preference class.

Specifically, we have to modify several files :

== MutableLinearPreferenceImpl.java

* LinkedList<Alternative> list become List<Alternative> list

* Delete the constructor and the factory method which take a Graph in parameter

* Modify equals() and hashcode() to respect the BP Local design

* Rename deleteAlternative(Alternative a) to removeAlternative(Alternative a)

* Transitively close the graph in the whole class (constructors + methods), and recalculate the closure after each modification

== MutableLinearPreferenceImplTest.java

* Add a test that verifies that the graph returned by asGraph is transitively closed and a test that affects g = pref.asGraph() then modifies pref then verifies that g has changed as it should

* Modify all existing tests using the constructor that takes a list as a parameter

* Test the decorators

== MutableLinearSetDecorator.java

In this class, we have to override methods likely to break the linearity of preference by the set.

@Override
	public boolean add(Alternative a) {
		
	}
@Override
	public boolean addAll(Collection<? extends Alternative> c) {
		
	}
@Override
	public boolean remove(Alternative a) {
		
	}
@Override
	public boolean removeAll(Collection<? extends Alternative> c) {
		
	}
@Override
	public boolean clear() {
		
	}
@Override
	public boolean retainAll(Collection<? extends Alternative> c) {
		
	}

== MutableLinearGraphDecorator.java

In this class, we have to override methods likely to break the linearity of preference by the graph.

@Override
	public boolean addNode(N node) {
		
	}
@Override
	public boolean putEdge(N nodeU, N nodeV) {
		
	}
@Override
	public boolean removeEdge(N nodeU, N nodeV) {
		
	}
@Override
	public boolean removeNode(N node) {
		
	}

