= Iteration 4

== First part of missions : correction of Iteration 3 following your feedback +

* Update of the GUI sketch by removing alternatives and voters boxes and by upgrading its comments : _Thomas_

* Correction of the sequence diagram : _Julien_

* Small modifications according to your feedback : _Pierre_


==  Second part of missions : additional information +

* Creation of an old GUI documentation table with a brief summarize of the Javadoc and an explanation of each method : _Thomas, Jade, Pierre & Léo_

* Reflexion of the MVC pattern to use it in our GUI : _Thomas, Jade, Pierre, Julien & Léo_

* Suggestion of a new class diagram for the GUI : _Julien_

* Creation of the GUI class diagram in Papyrus : _Julien & Pierre_

* Update of the new GUI use case diagram : _Thomas & Jade_

* Update of the MutableLinearPreference annex file explaining the new objective. This job consisted in working on the MutableLinearPreference, the 2 decorators and the future MutableStrictProfile. To this end, we created a Profile class diagram to help us better understand those : _Thomas & Jade_

