= Preferences Interface Diagram Documentation

=== Preference
A Preference is the ranking between Alternatives.

=== MutablePreference
A Preference where you can add Alternatives (only one by one). +
You can also add two relations between Alternatives : 

* The first one is "At least as good".
* The second one is "Equivalence".

=== AntiSymmetricPreference
A Preference where there is no "Equivalence" relation between Alternatives. +
The only possible relation is "Greater than".

=== ImmutablePreference
A Preference where can't add Alternatives and any relations.

=== MutableAntiSymmetricPreference
An AntiSymmetricPreference where you can add Alternatives (only one by one).

=== ImmutableAntySymmetricPreference
An AntiSymmetricPreference where you can't add Alternatives and relations.

=== CompletePreference
An ImmutablePreference where all the Alternatives have a two-to-one relation. +
A CompletePreference represents a complete preorder, also called a weak order.

=== LinearPreference
A CompletePreference and an AntiSymmetricPreference.

